spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        hibernate.cache.use_second_level_cache: true
        hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
